config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :mastercars
  resources :masters
  resources :grade
  resources :blogs
  resources :assistance
  resources :contact
  resources :carpark
  resources :service
  resources :company
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, length: { maximum: 140 }, presence: true
  validates :body, length: { minimum: 50 }, presence: true
end

app/models/card.rb
class Card < ApplicationRecord
    validates  :strana, :strana1, :truck, :driver, :manager, :rating, presence: true
end

app/models/master.rb
class Master < ApplicationRecord
  validates  :strana, :strana1, :truck, :driver, :manager, :rating, presence: true 
end

app/models/mastercar.rb
class Mastercar < ApplicationRecord
  validates  :strana, :strana1, :truck, :driver, :manager, :rating, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all.order("created_at DESC")
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = Card.all
    @cards = Card.order(created_at: :desc)
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to "/cards"
    # respond_to do |format|
    #   if @card.save
    #     format.html { redirect_to card_url(@card), notice: "Отзыв родился!" }
    #     format.json { render :show, status: :created, location: @card }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @card.errors, status: :unprocessable_entity }
    #   end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:strana, :strana1, :truck, :driver, :manager, :rating)
    end
end

app/controllers/carpark_controller.rb
class CarparkController < ApplicationController
  def index
  end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def index
  end
end

app/controllers/grade_controller.rb
class GradeController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assistance_helper.rb
module AssistanceHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
  def range2
    arr = []
    @cards.each do |card|
    arr << card.rating
    end
    f = arr.inject{ |sum, el| sum + el }.to_f / arr.size
    f.round(2)
  end

  def proc2
    t = range2 * 10
    t.round(2)
  end
end

app/helpers/carpark_helper.rb
module CarparkHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/grade_helper.rb
module GradeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mastercars_helper.rb
module MastercarsHelper
  def range1
    arr = []
    @mastercars.each do |mastercar|
    arr << mastercar.rating
    end
    f = arr.inject{ |sum, el| sum + el }.to_f / arr.size
    f.round(2)
  end

  def proc1
    t = range1 * 10
    t.round(2)
  end
end

app/helpers/masters_helper.rb
module MastersHelper
  def range
    arr = []
    @masters.each do |master|
    arr << master.rating
    end
    f = arr.inject{ |sum, el| sum + el }.to_f / arr.size
    f.round(2)
  end

  def proc
    t = range * 10
    t.round(2)
  end

end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/blogs/_blog.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>
    <body>
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div>

            <h4><p style="text-align: center;"><%= blog.title %></p></h4>

            <p>
              <font size="5"><%= blog.body %></font>

            </p>

          </div>

    </div>
  </div>
</div>
  </body>
</html>

app/views/blogs/_form.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>
    <body>
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <%= form_with(model: blog) do |form| %>
            <% if blog.errors.any? %>
              <div style="color: red">
                <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

                <ul>
                  <% blog.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div>
              <%= form.label :Название_статьи, class: "form-label", style: "display: block" %>
              <%= form.text_field :title, class: "form-control" %>
            </div><br>

            <div>
              <%= form.label :Статья, class: "form-label", style: "display: block" %>
              <%= form.text_area :body, class: "form-control"%>
            </div><br>

            <div>
            <%= form.submit "Записать", class:"btn btn-outline-primary" %>
            </div>
          <% end %>

    </div>
  </div>
</div>
  </body>
</html>

app/views/blogs/edit.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>
    <body class="page-id-6">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h3>Редактировать</h3>

          <%= render "form", blog: @blog %>

          <br>

          <div>
            <%= link_to "Показать", @blog %> |
            <%= link_to "Назад", blogs_path %>
          </div>

    </div>
  </div>
</div>
  </body>
</html>

app/views/blogs/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>
    <body class="page-id-6">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h3>Наш Блог</h3>
          <%= link_to "Добавить Новость", new_blog_path %><hr>
          <p style="color: green"><%= notice %></p>
          <div id="blogs">
            <% @blogs.each do |blog| %>
              <%= blog.title %>
              <p>
                <%= link_to "Показать статью", blog %>
              </p>
            <% end %>
          </div>

    </div>
  </div>
</div>
  </body>
</html>

app/views/blogs/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </head>
    <body class="page-id-6">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h3>Что-то новенькое</h3>

          <%= render "form", blog: @blog %>

          <br>

          <div>
            <%= link_to "Назад", blogs_path %>
          </div>

    </div>
  </div>
</div>
  </body>
</html>

app/views/blogs/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>
    <body class="page-id-6">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <p style="color: green"><%= notice %></p>

          <%= render @blog %>

          <div>
            <%= link_to "Редактировать", edit_blog_path(@blog) %> |
            <%= link_to "Назад", blogs_path %>

            <%= button_to "Удалить", @blog, method: :delete, class:"btn btn-sm btn-danger", style:"--bs-btn-padding-y: .20rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .65rem;" %>
          </div>

    </div>
  </div>
</div>
  </body>
</html>

app/views/cards/_card.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </head>
    <body class="page-id-8">
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div id="<%= dom_id card %>">
        <p>
          <strong>Страна отправления:</strong>
          <%= card.strana %> -
          <strong>Страна назначения:</strong>
          <%= card.strana1 %>
        </p>

  <p>
    <strong>Подвижной состав:</strong>
    <%= card.truck %>
  </p>

  <p>
    <strong>Водитель:</strong>
    <%= card.driver %>
  </p>

  <p>
    <strong>Логист:</strong>
    <%= card.manager %>
  </p>

  <p>
    <strong>Оценка:</strong>
    <%= card.rating %>
  </p>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/cards/_form.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </head>
    <body class="page-id-8">
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <img src="/61.png" alt="smile" width="50" height="50" style='position:absolute;left:420px;top:150px;'>

<%= form_with(model: card) do |form| %>
  <% if card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12">

      <div>
        <%= form.label :strana, "Страна отправления",class:"fw-semibold", style: "display: block" %>
        <select id = "strana" name = "card[strana]" class="form-select form-select-md mb-3" aria-label=".form-select-md example">
      <option selected disabled value="">Выбери страну</option>
      <option value="BY">BY</option>
      <option value="RUS">RUS</option>
      <option value="KZ">KZ</option>
      <option value="UZ">UZ</option>
      <option value="KG">KG</option>
      <option value="ЯУРОПА">ЯУРОПА</option>
        </select>
      </div>

      <div>
        <%= form.label :strana1, "Страна назначения",class:"fw-semibold", style: "display: block" %>
        <select id = "strana1" name = "card[strana1]" class="form-select form-select-md mb-3" aria-label=".form-select-md example">
      <option value="">Выбери страну</option>
      <option value="BY">BY</option>
      <option value="RUS">RUS</option>
      <option value="KZ">KZ</option>
      <option value="UZ">UZ</option>
      <option value="KG">KG</option>
      <option value="ЯУРОПА">ЯУРОПА</option>

        </select>
      </div>

      <div>
        <%= form.label :truck, "Подвижной состав",class:"fw-semibold", style: "display: block" %>
        <select id = "truck" name = "card[truck]" class="form-select form-select-md mb-3" aria-label=".form-select-md example">
      <option value="">Оцени подвижной состав</option>
      <option value="Отличный">Отличный</option>
      <option value="Плохой">Плохой</option>
      <option value="Нормальный">Нормальный</option>
      <option value="Видели и лучше">Видели и лучше</option>
      <option value="Довез и слава Богу">Довез и слава Богу</option>
        </select>
      </div>

      <div>
        <%= form.label :driver, "Водитель",class:"fw-semibold", style: "display: block" %>
        <select id = "driver" name = "card[driver]" class="form-select form-select-md mb-3" aria-label=".form-select-md example">
      <option value="">Оцени водителя</option>
      <option value="Шикарен">Шикарен</option>
      <option value="Отличный">Отличный</option>
      <option value="Мастер">Мастер</option>
      <option value="Как-то не очень">Как-то не очень</option>
      <option value="Человек на своем месте">Человек на своем месте</option>
      <option value="Профессионал">Профессионал</option>
      <option value="Довез и слава Богу">Довез и слава Богу</option>
        </select>
      </div>

      <div>
        <%= form.label :manager, "Логист",class:"fw-semibold", style: "display: block" %>
        <select id = "manager" name = "card[manager]" class="form-select form-select-md mb-3" aria-label=".form-select-md example">
      <option value="">Оцени логиста</option>
      <option value="Мастер своего дела">Мастер своего дела</option>
      <option value="Бог перевозок">Бог перевозок</option>
      <option value="Мы не общались">Мы не общались</option>
      <option value="Перевозка закончилась и слава богу">Перевозка закончилась и слава богу</option>
      <option value="Просто ...">Просто ...</option>
      <option value="Я надеюсь его уволили">Я надеюсь его уволили</option>
      <option value="Довез и слава Богу">Довез и слава Богу</option>
        </select>
      </div>

      <div>
        <%= form.label :rating, "Оценка",class:"fw-semibold", style: "display: block" %>
        <select id = "rating" name = "card[rating]" class="form-select form-select-md mb-3" aria-label=".form-select-md example">
      <option value="">Поставь оценку</option>
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
      <option value="6">6</option>
      <option value="7">7</option>
      <option value="8">8</option>
      <option value="9">9</option>
      <option value="10">10</option>
      </select>
      </div>

      <div>
        <%= form.submit 'Создать', class:"btn btn-sm btn-danger rounded-pill" %>
      </div>
    <% end %>
        </div>
      </div>
    </div>
  </body>
  </html>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Show this card", @card %> |
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script> -->
  </head>
    <body class="page-id-8">
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <p style="color: green"><%= notice %></p>
      <body class="image" background="15.jpg"><br>
      <font size="6.5" color="black" face="Tahoma">CardiTrans (<%= send(:range2) %>)</font>
      <a href="/grade"><img src="/60.png" alt="company" width="100" height="50" style='position:absolute;right:150px;top:150px;'></a>

      <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: <%= send(:proc2) %>%;" aria-valuenow="<%= send(:proc2) %>" aria-valuemin="0" aria-valuemax="10"><%= send(:proc2) %>%</div>
      </div>
      <br><p> <%= link_to "Новый отзыв", new_card_path %> </p><hr>

<% @cards.each do |card| %>
<div class="dropdown d-grid gap-2">
  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"><%= "Отзыв № #{card.id}"%></button><hr>
  <ul class="dropdown-menu">
    <li><a><%= render card %></a></li>
    </ul>
  <% end %>
    </div>
  </div>
</div>
</body>
</html>

app/views/cards/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </head>
    <body class="page-id-8">
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <br><h5>Оставь отзыв и спи спокойно</h5>

<%= render "form", card: @card %>

    </div>
  </div>
</div>
</body>
</html>

app/views/cards/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body class="page-id-8">
<div class="container">
  <div class="row">
    <div class="col-xs-12">
     <br><h5>Отзыв № <%= @card.id %></h5>
  <p><%= render @card %> </p>

    </div>
  </div>
</div>
</body>
</html>