config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :mastercars
  resources :masters
  resources :grade
  resources :blogs
  resources :assistance
  resources :contact
  resources :carpark
  resources :service
  resources :company
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, length: { maximum: 140 }, presence: true
  validates :body, length: { minimum: 50 }, presence: true
end

app/models/card.rb
class Card < ApplicationRecord
    validates  :strana, :strana1, :truck, :driver, :manager, :rating, presence: true
end

app/models/master.rb
class Master < ApplicationRecord
  validates  :strana, :strana1, :truck, :driver, :manager, :rating, presence: true 
end

app/models/mastercar.rb
class Mastercar < ApplicationRecord
  validates  :strana, :strana1, :truck, :driver, :manager, :rating, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all.order("created_at DESC")
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = Card.all
    @cards = Card.order(created_at: :desc)
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to "/cards"
    # respond_to do |format|
    #   if @card.save
    #     format.html { redirect_to card_url(@card), notice: "Отзыв родился!" }
    #     format.json { render :show, status: :created, location: @card }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @card.errors, status: :unprocessable_entity }
    #   end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:strana, :strana1, :truck, :driver, :manager, :rating)
    end
end

app/controllers/carpark_controller.rb
class CarparkController < ApplicationController
  def index
  end
end

app/controllers/grade_controller.rb
class GradeController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mastercars_controller.rb
class MastercarsController < ApplicationController
  before_action :set_mastercar, only: %i[ show edit update destroy ]

  # GET /mastercars or /mastercars.json
  def index
    @mastercars = Mastercar.all
    @mastercars = Mastercar.order(created_at: :desc)
  end

  # GET /mastercars/1 or /mastercars/1.json
  def show
  end

  # GET /mastercars/new
  def new
    @mastercar = Mastercar.new
  end

  # GET /mastercars/1/edit
  def edit
  end

  # POST /mastercars or /mastercars.json
  def create
    @mastercar = Mastercar.new(mastercar_params)
    if @mastercar.save
      redirect_to "/mastercars"
    # respond_to do |format|
    #   if @mastercar.save
    #     format.html { redirect_to mastercar_url(@mastercar), notice: "Отзыв родился!" }
    #     format.json { render :show, status: :created, location: @mastercar }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @mastercar.errors, status: :unprocessable_entity }
    #   end
    end
  end

  # PATCH/PUT /mastercars/1 or /mastercars/1.json
  def update
    respond_to do |format|
      if @mastercar.update(mastercar_params)
        format.html { redirect_to mastercar_url(@mastercar), notice: "Mastercar was successfully updated." }
        format.json { render :show, status: :ok, location: @mastercar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mastercar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mastercars/1 or /mastercars/1.json
  def destroy
    @mastercar.destroy

    respond_to do |format|
      format.html { redirect_to mastercars_url, notice: "Mastercar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mastercar
      @mastercar = Mastercar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mastercar_params
      params.require(:mastercar).permit(:strana, :strana1, :truck, :driver, :manager, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assistance_helper.rb
module AssistanceHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
  def range2
    arr = []
    @cards.each do |card|
    arr << card.rating
    end
    f = arr.inject{ |sum, el| sum + el }.to_f / arr.size
    f.round(2)
  end

  def proc2
    t = range2 * 10
    t.round(2)
  end
end

app/helpers/carpark_helper.rb
module CarparkHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/grade_helper.rb
module GradeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mastercars_helper.rb
module MastercarsHelper
  def range1
    arr = []
    @mastercars.each do |mastercar|
    arr << mastercar.rating
    end
    f = arr.inject{ |sum, el| sum + el }.to_f / arr.size
    f.round(2)
  end

  def proc1
    t = range1 * 10
    t.round(2)
  end
end

app/helpers/masters_helper.rb
module MastersHelper
  def range
    arr = []
    @masters.each do |master|
    arr << master.rating
    end
    f = arr.inject{ |sum, el| sum + el }.to_f / arr.size
    f.round(2)
  end

  def proc
    t = range * 10
    t.round(2)
  end

end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/mastercars/_form.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </head>
    <body class="page-id-8">
    <div class="container">
  <div class="row">
    <div class="col-xs-12">
      <img src="/61.png" alt="smile" width="50" height="50" style='position:absolute;left:420px;top:150px;'>

<%= form_with(model: mastercar) do |form| %>
  <% if mastercar.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mastercar.errors.count, "error") %> prohibited this mastercar from being saved:</h2>

      <ul>
        <% mastercar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12">

      <div>
        <%= form.label :strana, "Страна отправления",class:"fw-semibold", style: "display: block" %>
        <select id = "strana" name = "mastercar[strana]" class="form-select form-select-md mb-3" aria-label=".form-select-md example">
      <option selected disabled value="">Выбери страну</option>
      <option value="BY">BY</option>
      <option value="RUS">RUS</option>
      <option value="KZ">KZ</option>
      <option value="UZ">UZ</option>
      <option value="KG">KG</option>
        </select>
      </div>

      <div>
        <%= form.label :strana1, "Страна назначения",class:"fw-semibold", style: "display: block" %>
        <select id = "strana1" name = "mastercar[strana1]" class="form-select form-select-md mb-3" aria-label=".form-select-md example">
      <option value="">Выбери страну</option>
      <option value="BY">BY</option>
      <option value="RUS">RUS</option>
      <option value="KZ">KZ</option>
      <option value="UZ">UZ</option>
      <option value="KG">KG</option>
        </select>
      </div>

      <div>
        <%= form.label :truck, "Подвижной состав",class:"fw-semibold", style: "display: block" %>
        <select id = "truck" name = "mastercar[truck]" class="form-select form-select-md mb-3" aria-label=".form-select-md example">
      <option value="">Оцени подвижной состав</option>
      <option value="Отличный">Отличный</option>
      <option value="Плохой">Плохой</option>
      <option value="Нормальный">Нормальный</option>
      <option value="Видели и лучше">Видели и лучше</option>
      <option value="Довез и слава Богу">Довез и слава Богу</option>
        </select>
      </div>

      <div>
        <%= form.label :driver, "Водитель",class:"fw-semibold", style: "display: block" %>
        <select id = "driver" name = "mastercar[driver]" class="form-select form-select-md mb-3" aria-label=".form-select-md example">
      <option value="">Оцени водителя</option>
      <option value="Шикарен">Шикарен</option>
      <option value="Отличный">Отличный</option>
      <option value="Мастер">Мастер</option>
      <option value="Просто ...">Просто ...</option>
      <option value="Человек на своем месте">Человек на своем месте</option>
      <option value="Профессионал">Профессионал</option>
      <option value="Довез и слава Богу">Довез и слава Богу</option>
        </select>
      </div>

      <div>
        <%= form.label :manager, "Логист",class:"fw-semibold", style: "display: block" %>
        <select id = "manager" name = "mastercar[manager]" class="form-select form-select-md mb-3" aria-label=".form-select-md example">
      <option value="">Оцени логиста</option>
      <option value="Мастер своего дела">Мастер своего дела</option>
      <option value="Бог перевозок">Бог перевозок</option>
      <option value="Мы не общались">Мы не общались</option>
      <option value="Перевозка закончилась и слава богу">Перевозка закончилась и слава богу</option>
      <option value="Просто ...">Просто ...</option>
      <option value="Я надеюсь его уволили">Я надеюсь его уволили</option>
      <option value="Довез и слава Богу">Довез и слава Богу</option>
        </select>
      </div>

      <div>
        <%= form.label :rating, "Оценка",class:"fw-semibold", style: "display: block" %>
        <select id = "rating" name = "mastercar[rating]" class="form-select form-select-md mb-3" aria-label=".form-select-md example">
      <option value="">Поставь оценку</option>
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
      <option value="6">6</option>
      <option value="7">7</option>
      <option value="8">8</option>
      <option value="9">9</option>
      <option value="10">10</option>
      </select>
      </div>

      <div>
        <%= form.submit 'Создать', class:"btn btn-sm btn-danger rounded-pill" %>
      </div>
    <% end %>
        </div>
      </div>
    </div>
</body>
</html>

app/views/mastercars/_mastercar.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </head>
    <body class="page-id-8">
    <div class="container">
  <div class="row">
    <div class="col-xs-12">
        <div id="<%= dom_id mastercar %>">
  <p>
    <strong>Страна отправления:</strong>
    <%= mastercar.strana %> -
    <strong>Страна назначения:</strong>
    <%= mastercar.strana1 %>
  </p>

  <p>
    <strong>Подвижной состав:</strong>
    <%= mastercar.truck %>
  </p>

  <p>
    <strong>Водитель:</strong>
    <%= mastercar.driver %>
  </p>

  <p>
    <strong>Логист:</strong>
    <%= mastercar.manager %>
  </p>

  <p>
    <strong>Оценка:</strong>
    <%= mastercar.rating %>
  </p>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/mastercars/edit.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </head>
    <body class="page-id-8">
      <div class="container">
  <div class="row">
    <div class="col-xs-12">
      <br><h5>Исправь отзыв</h5>

<%= render "form", master: @mastercar %>

<br>

<div>
  <%= link_to "Показать этот отзыв", @mastercar %> |
  <%= link_to "Назад", mastercars_path %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/mastercars/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script> -->

    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script> -->

    <title>MasterLogistik</title>
  </head>
  <body class="page-id-8">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <p style="color: green"><%= notice %></p>
      <font size="6.5" color="black" face="Tahoma">МастерКаргоРус (<%= send(:range1) %>)</font>
      <a href="/grade"><img src="/60.png" alt="company" width="100" height="50" style='position:absolute;right:150px;top:150px;'></a>

      <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: <%= send(:proc1) %>%;" aria-valuenow="<%= send(:proc1) %>" aria-valuemin="0" aria-valuemax="10"><%= send(:proc1) %>%</div>
      </div>
      <br><p> <%= link_to "Новый отзыв", new_mastercar_path %> </p><hr>

      <% @mastercars.each do |mastercar| %>
      <div class="dropdown d-grid gap-2">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"><%= "Отзыв № #{mastercar.id}"%></button><hr>
         <ul class="dropdown-menu">
           <li><a><%= render mastercar %></a></li>
        </ul>
        <% end %>
        </div>

    </div>
  </div>
</div>
  </body>
</html>

app/views/mastercars/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </head>
    <body class="page-id-8">
    <div class="container">
  <div class="row">
    <div class="col-xs-12">
      <br><h5>Оставь отзыв и спи спокойно</h5>

<%= render "form", mastercar: @mastercar %>

    </div>
  </div>
</div>
</body>
</html>

app/views/mastercars/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MasterLogistik</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </head>
    <body class="page-id-8">
    <div class="container">
  <div class="row">
    <div class="col-xs-12">
     <br><h5>Отзыв № <%= @mastercar.id %></h5>
  <p> <%= render @mastercar %> </p>

    </div>
  </div>
</div>
</body>
</html>